title: Spin Cycle
description: >-
  Platform automation at scale
baseurl: /spincycle
twitter_username: square
github_username: square
markdown: kramdown
plugins:
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

remote_theme: pmarsceill/just-the-docs@v0.2.8
search_enabled: true
aux_links:
  "Spin Cycle":
    - "//github.com/square/spincycle"
